const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const db={phones:[
["iPhone 15","Apple","€799","6.1 OLED","48 MP","3349 mAh"],["iPhone 15 Pro","Apple","€999","6.1 OLED","48 MP","3274 mAh"],["iPhone 16","Apple","€899","6.1 OLED","48 MP","3561 mAh"],["iPhone 16 Pro","Apple","€1,199","6.3 OLED","48 MP","3582 mAh"],["Galaxy S24","Samsung","€899","6.2 AMOLED","50 MP","4000 mAh"],["Galaxy S24 Ultra","Samsung","€1,449","6.8 AMOLED","200 MP","5000 mAh"],["Galaxy S25","Samsung","€949","6.2 AMOLED","50 MP","4000 mAh"],["Galaxy S25 Ultra","Samsung","€1,449","6.9 AMOLED","200 MP","5000 mAh"],["Pixel 9","Google","€899","6.3 OLED","50 MP","4700 mAh"],["Pixel 9 Pro","Google","€999","6.3 OLED","50 MP","4700 mAh"],["OnePlus 13","OnePlus","€999","6.82 AMOLED","50 MP","6000 mAh"],["Xiaomi 14","Xiaomi","€899","6.36 AMOLED","50 MP","4610 mAh"]],
laptops:[["MacBook Air M3","Apple","€1,099","13.6","8 GB","18 h"],["MacBook Pro 14 M4","Apple","€1,999","14.2","16 GB","24 h"],["Dell XPS 13","Dell","€1,099","13.4","16 GB","19 h"],["ThinkPad X1 Carbon","Lenovo","€1,499","14","16 GB","19 h"],["ASUS Zenbook 14","ASUS","€899","14 OLED","16 GB","15 h"],["ROG Zephyrus G14","ASUS","€1,799","14 OLED","32 GB","12 h"],["HP Spectre x360","HP","€1,399","14 OLED","16 GB","16 h"],["Acer Swift Go 14","Acer","€799","14 OLED","16 GB","12 h"]],
cars:[["Tesla Model 3","Tesla","€39,990","283 hp","513 km","6.1 s"],["Tesla Model Y","Tesla","€44,990","347 hp","533 km","5.0 s"],["BMW 3 Series","BMW","€49,500","184 hp","650 km","7.4 s"],["BMW 5 Series","BMW","€61,000","208 hp","700 km","7.5 s"],["Mercedes C-Class","Mercedes","€52,000","170 hp","700 km","8.6 s"],["Mercedes E-Class","Mercedes","€65,000","204 hp","750 km","7.5 s"],["Audi A4","Audi","€47,000","150 hp","680 km","8.6 s"],["Audi A6","Audi","€58,000","204 hp","730 km","7.8 s"],["Toyota Camry","Toyota","€38,500","230 hp","800 km","7.2 s"],["Toyota RAV4","Toyota","€39,000","218 hp","850 km","8.1 s"],["Volkswagen Golf","Volkswagen","€27,000","150 hp","700 km","8.5 s"],["Dacia Duster","Dacia","€19,000","140 hp","800 km","10.2 s"]]};
function fill(){let a=db[$("#cat").value],o=a.map((x,i)=>`<option value="${i}">${x[0]} — ${x[1]}</option>`).join("");$("#a").innerHTML=o;$("#b").innerHTML=o;$("#b").selectedIndex=1;filterMatches()}
function filterMatches(){let a=db[$("#cat").value],q=$("#prodSearch").value.toLowerCase();$("#matches").innerHTML=a.filter(x=>x[0].toLowerCase().includes(q)||x[1].toLowerCase().includes(q)).slice(0,15).map((x)=>`<button class="match" data-name="${x[0]}">${x[0]}</button>`).join("");$$(".match").forEach(x=>x.onclick=()=>{let i=a.findIndex(v=>v[0]===x.dataset.name);$("#a").value=i;compare()})}
function compare(){let a=db[$("#cat").value],x=a[+$("#a").value],y=a[+$("#b").value],labs=["Brand","Preț","Ecran / tip","Cameră / putere","Baterie / autonomie"];$("#result").innerHTML=`<div class="table"><div class="head">Caracteristică</div><div class="head">${x[0]}</div><div class="head">${y[0]}</div>${labs.map((l,i)=>`<div>${l}</div><div>${x[i+1]}</div><div>${y[i+1]}</div>`).join("")}</div>`}
$("#cat").onchange=()=>{fill();compare()};$("#prodSearch").oninput=filterMatches;$("#compareBtn").onclick=compare;fill();compare();
function modal(t){let bodies={rewrite:["Rescrie natural","Scrie textul pe care vrei să-l îmbunătățești."],description:["Descriere produs","Ex.: căști wireless, ANC, autonomie 30h."],translate:["Traducător","Scrie textul de tradus."],image:["Image Prompt","Descrie imaginea dorită." ]};if(["rewrite","description","translate","image"].includes(t)){$("#body").innerHTML=`<div class="tool"><h2>${bodies[t][0]}</h2><p>${bodies[t][1]}</p><textarea class="tooltextarea" id="input" rows="7"></textarea><div class="toolactions"><button class="primary" id="run">Generează</button><button class="secondary" id="copy">Copiază</button></div><div class="output" id="out"></div></div>`;$("#run").onclick=()=>{let v=$("#input").value.trim();$("#out").textContent=t==="image"?`Create a premium photorealistic image of ${v}. Professional lighting, clean composition, realistic materials, commercial advertising quality, 4K.`:t==="rewrite"?`Variantă îmbunătățită:\n\n${v.replace(/\s+/g," ")}`:t==="description"?`Descriere produs:\n\nDescoperă ${v}. O alegere practică, modernă și potrivită pentru utilizarea de zi cu zi.`:`Text primit:\n\n${v}\n\n[Motorul AI de traducere va fi conectat prin API.]`;};$("#copy").onclick=()=>navigator.clipboard?.writeText($("#out").innerText);return}
let b={percent:["Calculator procent","Valoare","Procent %"],vat:["Calculator TVA","Sumă","TVA %"],password:["Generator parole","Lungime",""],units:["Conversie unități","Valoare",""],age:["Calculator vârstă","Data nașterii",""],qr:["QR Code","Link",""]}[t];$("#body").innerHTML=`<div class="tool"><h2>${b[0]}</h2><input class="toolinput" id="v1" type="${t==="age"?"date":"number"}" placeholder="${b[1]}"><input class="toolinput" id="v2" type="number" placeholder="${b[2]}" value="${t==="password"?"18":""}"><button class="primary" id="run">Calculează</button><div class="output" id="out"></div></div>`;$("#run").onclick=()=>{let x=$("#v1").value,y=+$("#v2").value,o=$("#out");if(t==="percent")o.textContent=`${y}% din ${x} = ${(x*y/100).toFixed(2)}`;if(t==="vat"){let z=x*y/100;o.textContent=`TVA: ${z.toFixed(2)}\nTotal: ${(x+z).toFixed(2)}`};if(t==="password"){let c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";let u=new Uint32Array(+x||18);crypto.getRandomValues(u);o.textContent=[...u].map(n=>c[n%c.length]).join("")};if(t==="units")o.textContent=`${x} km = ${(x*.621371).toFixed(3)} mile`;if(t==="age"){let d=new Date(x),n=new Date(),a=n.getFullYear()-d.getFullYear();if(new Date(n.getFullYear(),d.getMonth(),d.getDate())>n)a--;o.textContent=`Vârsta: ${a} ani`};if(t==="qr")o.innerHTML=`<img alt="QR" src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(x)}">`};}
$$(".open").forEach(b=>b.onclick=()=>{modal(b.dataset.tool);$("#modal").hidden=false});$("#close").onclick=()=>$("#modal").hidden=true;$(".backdrop").onclick=()=>$("#modal").hidden=true;
$("#search").oninput=e=>{let q=e.target.value.toLowerCase(),n=0;$$(".searchable").forEach(x=>{let ok=!q||x.dataset.search.includes(q);x.style.display=ok?"":"none";if(ok)n++});$("#none").hidden=n>0};document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search").focus()}if(e.key==="Escape")$("#modal").hidden=true};
$$(".chips button").forEach(x=>x.onclick=()=>{location.hash="compare";$("#cat").value=x.dataset.cat;fill();compare()});$("#theme").onclick=()=>{document.body.classList.toggle("light");localStorage.theme=document.body.classList.contains("light")?"1":"0"};if(localStorage.theme==="1")document.body.classList.add("light");
